# -*- coding: utf-8 -*-
"""Untitled3.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1tc7XKPLfGtOfpyYxW6VJc7Aj2gCi-Ycf
"""

import torch
import torch.nn as nn
import torch.nn.functional as F
import torchvision.ops as ops
import kagglehub
from PIL import Image
import numpy as np
import os
import pandas as pd

path = kagglehub.dataset_download("sbaghbidi/human-faces-object-detection")
BASE = os.path.join(path, "images")

print(os.listdir(path))

labels_df = pd.read_csv(os.path.join(path, "faces.csv"))
print(len(labels_df))

label_cache = []
for _, row in labels_df.iterrows():
    img_name = row['image_name']
    if not os.path.exists(os.path.join(BASE, img_name)):
        continue

    w_orig, h_orig = row['width'], row['height']
    scale = min(512/w_orig, 512/h_orig)
    nw, nh = int(w_orig*scale), int(h_orig*scale)
    dx, dy = (512 - nw)//2, (512 - nh)//2

    img_boxes = []
    img_rows = labels_df[labels_df['image_name'] == img_name]

    for _, img_row in img_rows.iterrows():
        x0, y0, x1, y1 = img_row['x0'], img_row['y0'], img_row['x1'], img_row['y1']

        x0_norm = (x0/w_orig * scale + dx) / 512
        y0_norm = (y0/h_orig * scale + dy) / 512
        x1_norm = (x1/w_orig * scale + dx) / 512
        y1_norm = (y1/h_orig * scale + dy) / 512

        img_boxes.append([1.0, x0_norm, y0_norm, x1_norm, y1_norm])

    label_cache.append({
        'img_name': img_name,
        'boxes': np.array(img_boxes, dtype=np.float32)
    })

print(len(label_cache))

def letterbox_fast(img_array):
    h, w = img_array.shape[:2]
    scale = min(512/w, 512/h)
    nw, nh = int(w*scale), int(h*scale)
    img_resized = np.array(Image.fromarray(img_array).resize((nw, nh), Image.BILINEAR))
    pad_img = np.full((512, 512, 3), 114, dtype=np.uint8)
    dx, dy = (512 - nw)//2, (512 - nh)//2
    pad_img[dy:dy+nh, dx:dx+nw] = img_resized
    return pad_img

def data_generator(batch_size=8):
    files = [item['img_name'] for item in label_cache]

    while True:
        np.random.shuffle(files)
        for i in range(0, len(files), batch_size):
            batch_X, batch_Y = [], []
            for j in range(min(batch_size, len(files)-i)):
                fname = files[i+j]
                cache_item = next(item for item in label_cache if item['img_name'] == fname)
                img = np.array(Image.open(os.path.join(BASE,fname)).convert('RGB'))
                img_norm = letterbox_fast(img)

                batch_X.append(img_norm)
                batch_Y.append(cache_item['boxes'])
            X = torch.tensor(np.array(batch_X), dtype=torch.float32).permute(0,3,1,2) / 255.0
            max_b = max(y.shape[0] for y in batch_Y) if batch_Y else 1
            Y = torch.zeros(len(batch_Y), max_b, 5) - 1
            for k, y in enumerate(batch_Y):
                if y.shape[0] > 0:
                    Y[k, :y.shape[0]] = torch.from_numpy(y)
            yield X.cuda(), Y.cuda()

from collections import defaultdict

annotations_dict = defaultdict(list)

for _, row in labels_df.iterrows():
    fname = row["image_name"]
    if not os.path.exists(os.path.join(BASE, fname)):
        continue

    annotations_dict[fname].append([
        row["x0"], row["y0"],
        row["x1"], row["y1"]
    ])

annotations = [
    {"file": fname, "boxes": boxes}
    for fname, boxes in annotations_dict.items()
]

print("всего иображений:", len(annotations))

def generate_anchors(H, W, sizes, device):
    ys, xs = torch.meshgrid(
        torch.arange(H), torch.arange(W), indexing="ij"
    )
    xs = (xs + 0.5) / W
    ys = (ys + 0.5) / H

    anchors = []
    for s in sizes:
        w = h = s
        anchors.append(torch.stack([
            xs - w/2,ys - h/2, xs + w/2,ys + h/2], dim=-1))

    anchors = torch.stack(anchors, dim=-2)
    return anchors.reshape(-1, 4).clamp(0, 1).to(device)

from torch.utils.data import Dataset

class FaceDataset(Dataset):
    def __init__(self, img_dir, annotations, img_size=512):
        self.img_dir = img_dir
        self.ann = annotations
        self.img_size = img_size

    def __len__(self):
        return len(self.ann)

    def letterbox(self, img):
        w, h = img.size
        s = min(self.img_size / w, self.img_size / h)
        nw, nh = int(w*s), int(h*s)

        img = img.resize((nw, nh), Image.BILINEAR)
        canvas = Image.new("RGB", (self.img_size, self.img_size), (114,114,114))
        dx, dy = (self.img_size-nw)//2, (self.img_size-nh)//2
        canvas.paste(img, (dx, dy))

        return canvas, s, dx, dy

    def __getitem__(self, idx):
        item = self.ann[idx]

        img = Image.open(os.path.join(self.img_dir, item["file"])).convert("RGB")
        img, scale, dx, dy = self.letterbox(img)

        img = torch.from_numpy(np.array(img)).permute(2,0,1).float() / 255.

        boxes = []
        for x0,y0,x1,y1 in item["boxes"]:
            x0 = (x0*scale + dx) / self.img_size
            y0 = (y0*scale + dy) / self.img_size
            x1 = (x1*scale + dx) / self.img_size
            y1 = (y1*scale + dy) / self.img_size
            boxes.append([x0,y0,x1,y1])

        boxes = torch.tensor(boxes, dtype=torch.float32)
        return img, boxes

#sizes = [0.03, 0.05, 0.08, 0.12, 0.18]
#ratios = [0.8, 1.0, 1.25]
class MobileNet(nn.Module):
    def __init__(self):
        super().__init__()
        self.model = nn.Sequential(
            nn.Conv2d(3, 32, 3, 2, 1), nn.BatchNorm2d(32), nn.ReLU6(),
            nn.Conv2d(32, 32, 3, 1, 1, groups=32), nn.BatchNorm2d(32), nn.ReLU6(),
            nn.Conv2d(32, 64, 1), nn.BatchNorm2d(64), nn.ReLU6(),

            nn.Conv2d(64, 64, 3, 2, 1, groups=64), nn.BatchNorm2d(64), nn.ReLU6(),
            nn.Conv2d(64, 128, 1), nn.BatchNorm2d(128), nn.ReLU6(),

            nn.Conv2d(128, 128, 3, 2, 1, groups=128), nn.BatchNorm2d(128), nn.ReLU6(),
            nn.Conv2d(128, 256, 1), nn.BatchNorm2d(256), nn.ReLU6(),
        )

    def forward(self, x):
        return self.model(x)
class SSD(nn.Module):
    def __init__(self, num_classes=2):
        super().__init__()
        self.backbone = MobileNet()
        self.num_classes = num_classes

        self.sizes = [0.06, 0.1, 0.15]
        self.ratios = [0.5, 1.0, 1.5]
        self.num_anchors = len(self.sizes) * len(self.ratios)

        self.cls_head = nn.Conv2d(256, self.num_anchors * num_classes, 3, padding=1)
        self.box_head = nn.Conv2d(256, self.num_anchors * 4, 3, padding=1)

    def forward(self, x):
        feat = self.backbone(x)
        B, _, H, W = feat.shape

        cls = self.cls_head(feat)
        box = self.box_head(feat)

        cls = cls.permute(0,2,3,1).reshape(B, -1, self.num_classes)
        box = box.permute(0,2,3,1).reshape(B, -1, 4)

        anchors = self.generate_anchors(H, W, x.device)
        return anchors, cls, box

    def generate_anchors(self, H, W, device):
        ys, xs = torch.meshgrid(torch.arange(H), torch.arange(W), indexing="ij")
        xs = (xs + 0.5) / W
        ys = (ys + 0.5) / H

        anchors = []
        for s in self.sizes:
            for r in self.ratios:
                w = s * np.sqrt(r)
                h = s / np.sqrt(r)
                anchors.append(torch.stack([
                    xs - w/2, ys - h/2,
                    xs + w/2, ys + h/2
                ], dim=-1))
        anchors = torch.stack(anchors, dim=-2)
        return anchors.reshape(-1,4).clamp(0,1).to(device)

def encode_boxes(gt, anchors):
    ax = (anchors[:, 0] + anchors[:, 2]) / 2
    ay = (anchors[:, 1] + anchors[:, 3]) / 2
    aw = anchors[:, 2] - anchors[:, 0]
    ah = anchors[:, 3] - anchors[:, 1]

    gx = (gt[:, 0] + gt[:, 2]) / 2
    gy = (gt[:, 1] + gt[:, 3]) / 2
    gw = gt[:, 2] - gt[:, 0]
    gh = gt[:, 3] - gt[:, 1]

    dx = (gx - ax) / aw
    dy = (gy - ay) / ah
    dw = torch.log(gw / aw)
    dh = torch.log(gh / ah)

    return torch.stack([dx, dy, dw, dh], dim=1)
def decode_boxes(pred, anchors):
    ax = (anchors[:, 0] + anchors[:, 2]) / 2
    ay = (anchors[:, 1] + anchors[:, 3]) / 2
    aw = anchors[:, 2] - anchors[:, 0]
    ah = anchors[:, 3] - anchors[:, 1]

    gx = pred[:, 0] * aw + ax
    gy = pred[:, 1] * ah + ay
    gw = torch.exp(pred[:, 2]) * aw
    gh = torch.exp(pred[:, 3]) * ah

    return torch.stack([
        gx - gw/2, gy - gh/2,
        gx + gw/2, gy + gh/2
    ], dim=1)

def match_anchors(anchors, gt_boxes, iou_thresh=0.5):
    ious = ops.box_iou(anchors, gt_boxes)
    best_iou, best_gt = ious.max(dim=1)

    labels = torch.zeros(len(anchors), dtype=torch.long, device=anchors.device)
    labels[best_iou >= iou_thresh] = 1

    matched_gt = gt_boxes[best_gt]
    return labels, matched_gt

def ssd_loss(cls_pred, box_pred, anchors, gt_boxes, neg_ratio=3):
    if gt_boxes.numel() == 0:
        labels = torch.zeros(len(cls_pred), dtype=torch.long, device=cls_pred.device)
        return F.cross_entropy(cls_pred, labels)

    labels, matched_gt = match_anchors(anchors, gt_boxes)

    cls_loss_all = F.cross_entropy(cls_pred, labels, reduction="none")

    pos_mask = labels == 1
    neg_mask = labels == 0

    num_pos = pos_mask.sum()
    num_neg = min(neg_ratio * num_pos, neg_mask.sum())

    neg_loss = cls_loss_all[neg_mask]
    neg_topk, _ = torch.topk(neg_loss, k=num_neg)

    cls_loss = (
        cls_loss_all[pos_mask].sum() +
        neg_topk.sum()
    ) / (num_pos + num_neg + 1e-6)

    if num_pos > 0:
        box_tgt = encode_boxes(matched_gt[pos_mask], anchors[pos_mask])
        box_loss = F.smooth_l1_loss(box_pred[pos_mask], box_tgt)
    else:
        box_loss = torch.tensor(0., device=cls_pred.device)

    return cls_loss + 5 * box_loss

def train_one_epoch(net, loader, optimizer, device):
    net.train()
    total = 0

    for images, gt_boxes in loader:
        images = images.to(device)
        gt_boxes = gt_boxes.to(device)

        anchors, cls_pred, box_pred = net(images)

        loss = ssd_loss(
            cls_pred[0],
            box_pred[0],
            anchors,
            gt_boxes[0]
        )

        optimizer.zero_grad()
        loss.backward()
        optimizer.step()

        total += loss.item()

    return total / len(loader)

from torch.utils.data import DataLoader


dataset = FaceDataset(
    img_dir=BASE,
    annotations=annotations,
    img_size=512
)

train_loader = DataLoader(
    dataset,
    batch_size=1,
    shuffle=True,
    num_workers=2,
    pin_memory=True
)
device = "cuda" if torch.cuda.is_available() else "cpu"

net = SSD(num_classes=2).to(device)

optimizer = torch.optim.AdamW(
    net.parameters(),
    lr=1e-3,
    weight_decay=5e-4
)

num_epochs = 85
best_loss = float("inf")

for epoch in range(num_epochs):
    avg_loss = train_one_epoch(
        net,
        train_loader,
        optimizer,
        device
    )

    print(f"[Epoch {epoch+1:03d}] loss = {avg_loss:.4f}")

    if avg_loss < best_loss:
        best_loss = avg_loss
        torch.save(net.state_dict(), "best_ssd.pth")

import matplotlib.pyplot as plt
import matplotlib.patches as patches
from PIL import Image
import torch
import torchvision.ops as ops
import numpy as np
import torch.nn.functional as F

@torch.no_grad()
def predict_image(net, img_path, conf_thresh=0.05, iou_thresh=0.45, device='cuda'):
    net.eval()

    img = Image.open(img_path).convert('RGB')
    orig_w, orig_h = img.size
    img_array = np.array(img)

    h, w = img_array.shape[:2]
    scale = min(512 / w, 512 / h)
    nw, nh = int(w * scale), int(h * scale)

    img_resized = Image.fromarray(img_array).resize((nw, nh), Image.BILINEAR)
    img_pad = Image.new('RGB', (512, 512), (114, 114, 114))
    img_pad.paste(img_resized, ((512 - nw) // 2, (512 - nh) // 2))

    x = torch.from_numpy(np.array(img_pad)).permute(2, 0, 1).unsqueeze(0).float() / 255.
    x = x.to(device)

    anchors, cls_preds, bbox_preds = net(x)

    anchors = anchors.to(device)              # [N,4]
    cls_preds = cls_preds[0]                  # [N,2]
    bbox_preds = bbox_preds[0]                # [N,4]

    scores = F.softmax(cls_preds, dim=1)[:, 1]

    boxes = decode_boxes(bbox_preds, anchors)
    boxes = boxes.clamp(0, 1)

    keep = scores > conf_thresh
    if keep.sum() == 0:
        return np.array([]), np.array([])

    boxes = boxes[keep]
    scores = scores[keep]

    keep = ops.nms(boxes, scores, iou_thresh)
    boxes = boxes[keep]
    scores = scores[keep]

    boxes = boxes.cpu().numpy()
    scores = scores.cpu().numpy()

    pad_x, pad_y = (512 - nw) / 2, (512 - nh) / 2
    boxes[:, [0, 2]] = (boxes[:, [0, 2]] * 512 - pad_x) / scale
    boxes[:, [1, 3]] = (boxes[:, [1, 3]] * 512 - pad_y) / scale

    boxes[:, [0, 2]] = np.clip(boxes[:, [0, 2]], 0, orig_w)
    boxes[:, [1, 3]] = np.clip(boxes[:, [1, 3]], 0, orig_h)

    return boxes, scores



def show_detections(img_path, boxes, scores, conf_thresh=0.5):
    """Показать результаты"""
    img = Image.open(img_path)
    fig, ax = plt.subplots(1, figsize=(12, 12))
    ax.imshow(img)

    for box, score in zip(boxes, scores):
        if score > conf_thresh:
            x1, y1, x2, y2 = box
            rect = patches.Rectangle((x1, y1), x2-x1, y2-y1,
                                   linewidth=2, edgecolor='red', facecolor='none')
            ax.add_patch(rect)
            ax.text(x1, y1-10, f'Face: {score:.3f}', color='red', fontsize=12,
                   bbox=dict(boxstyle="round,pad=0.3", facecolor="yellow", alpha=0.5))

    plt.axis('off')
    plt.show()

device = 'cuda' if torch.cuda.is_available() else 'cpu'
net = SSD(num_classes=2).to(device)

net.load_state_dict(torch.load('best_ssd.pth', map_location=device))
net.eval()

img_path = "/content/sonya.jpg"
boxes, scores = predict_image(net, img_path, conf_thresh=0.05, iou_thresh=0.45)

print(f"Найдено лиц: {len(boxes)}")
show_detections(img_path, boxes, scores)

